# Generated by Django 4.0.1 on 2022-04-12 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 13, 13, 31, 29784, tzinfo=utc)),
        ),
    ]
